name: Test Vote Service

on:
  push:
    branches: [ "main" ]
    paths:
      - 'vote/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'vote/**'

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      # We need Docker in Docker for testcontainers
      dind:
        image: docker:dind
        ports:
          - 2375:2375
        env:
          DOCKER_TLS_CERTDIR: ""
        options: >-
          --privileged
          --health-cmd "docker info"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        working-directory: ./vote
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-test.txt

      - name: Run tests
        working-directory: ./vote
        env:
          DOCKER_HOST: tcp://localhost:2375
          TESTCONTAINERS_DOCKER_SOCKET_OVERRIDE: /var/run/docker.sock
          PYTHONPATH: ${{ github.workspace }}/vote
        run: |
          pytest test_vote_service.py -v
